analyzer:
  exclude:
    - test/**
    - example/**
    - "**/*.pb.dart"
    - "**/*.pbenum.dart"
    - "**/*.pbjson.dart"
    - "**/*.pbserver.dart"
  errors:
    unused_import: ignore
    unused_local_variable: ignore
    dead_code: ignore
    prefer_const_constructors: ignore
    directives_ordering: ignore
    sort_constructors_first: ignore
    NON_BOOL_OPERAND: error # Keep this one as error if it persists
    override_on_non_overriding_member: ignore
    unnecessary_non_null_assertion: ignore
    unused_field: ignore
    unnecessary_cast: ignore
    body_might_complete_normally_catch_error: ignore
    public_member_api_docs: ignore
    package_api_docs: ignore
    avoid_print: ignore
    unnecessary_null_comparison: ignore
    unnecessary_import: ignore
    unused_element: ignore
    unused_shown_name: ignore
    unused_catch_stack: ignore
    unused_local_variable: ignore
    unused_catch_clause: ignore
    undefined_shown_name: ignore
    doc_directive_has_invalid_argument: ignore
    strict_raw_type: ignore
    strict_inference: ignore
    strict_casts: ignore
