// Mocks generated by Mockito 5.4.6 from annotations
// in ipfs_libp2p/test/transport/p2p_stream_adapter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i10;
import 'dart:io' as _i6;
import 'dart:typed_data' as _i13;

import 'package:ipfs_libp2p/core/crypto/keys.dart' as _i11;
import 'package:ipfs_libp2p/core/multiaddr.dart' as _i3;
import 'package:ipfs_libp2p/core/network/conn.dart' as _i4;
import 'package:ipfs_libp2p/core/network/context.dart' as _i12;
import 'package:ipfs_libp2p/core/network/mux.dart' as _i14;
import 'package:ipfs_libp2p/core/network/rcmgr.dart' as _i5;
import 'package:ipfs_libp2p/core/network/stream.dart' as _i7;
import 'package:ipfs_libp2p/core/peer/peer_id.dart' as _i2;
import 'package:ipfs_libp2p/p2p/transport/tcp_connection.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePeerId_0 extends _i1.SmartFake implements _i2.PeerId {
  _FakePeerId_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMultiAddr_1 extends _i1.SmartFake implements _i3.MultiAddr {
  _FakeMultiAddr_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnState_2 extends _i1.SmartFake implements _i4.ConnState {
  _FakeConnState_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnStats_3 extends _i1.SmartFake implements _i4.ConnStats {
  _FakeConnStats_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConnScope_4 extends _i1.SmartFake implements _i5.ConnScope {
  _FakeConnScope_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSocket_5 extends _i1.SmartFake implements _i6.Socket {
  _FakeSocket_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeP2PStream_6<T> extends _i1.SmartFake implements _i7.P2PStream<T> {
  _FakeP2PStream_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePeerScope_7 extends _i1.SmartFake implements _i5.PeerScope {
  _FakePeerScope_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScopeStat_8 extends _i1.SmartFake implements _i5.ScopeStat {
  _FakeScopeStat_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResourceScopeSpan_9 extends _i1.SmartFake
    implements _i5.ResourceScopeSpan {
  _FakeResourceScopeSpan_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TCPConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockTCPConnection extends _i1.Mock implements _i8.TCPConnection {
  MockTCPConnection() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i9.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  _i2.PeerId get localPeer => (super.noSuchMethod(
        Invocation.getter(#localPeer),
        returnValue: _FakePeerId_0(
          this,
          Invocation.getter(#localPeer),
        ),
      ) as _i2.PeerId);

  @override
  _i2.PeerId get remotePeer => (super.noSuchMethod(
        Invocation.getter(#remotePeer),
        returnValue: _FakePeerId_0(
          this,
          Invocation.getter(#remotePeer),
        ),
      ) as _i2.PeerId);

  @override
  _i10.Future<_i11.PublicKey?> get remotePublicKey => (super.noSuchMethod(
        Invocation.getter(#remotePublicKey),
        returnValue: _i10.Future<_i11.PublicKey?>.value(),
      ) as _i10.Future<_i11.PublicKey?>);

  @override
  _i3.MultiAddr get localMultiaddr => (super.noSuchMethod(
        Invocation.getter(#localMultiaddr),
        returnValue: _FakeMultiAddr_1(
          this,
          Invocation.getter(#localMultiaddr),
        ),
      ) as _i3.MultiAddr);

  @override
  _i3.MultiAddr get remoteMultiaddr => (super.noSuchMethod(
        Invocation.getter(#remoteMultiaddr),
        returnValue: _FakeMultiAddr_1(
          this,
          Invocation.getter(#remoteMultiaddr),
        ),
      ) as _i3.MultiAddr);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
      ) as bool);

  @override
  _i4.ConnState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeConnState_2(
          this,
          Invocation.getter(#state),
        ),
      ) as _i4.ConnState);

  @override
  _i4.ConnStats get stat => (super.noSuchMethod(
        Invocation.getter(#stat),
        returnValue: _FakeConnStats_3(
          this,
          Invocation.getter(#stat),
        ),
      ) as _i4.ConnStats);

  @override
  _i5.ConnScope get scope => (super.noSuchMethod(
        Invocation.getter(#scope),
        returnValue: _FakeConnScope_4(
          this,
          Invocation.getter(#scope),
        ),
      ) as _i5.ConnScope);

  @override
  _i10.Future<List<_i7.P2PStream<dynamic>>> get streams => (super.noSuchMethod(
        Invocation.getter(#streams),
        returnValue: _i10.Future<List<_i7.P2PStream<dynamic>>>.value(
            <_i7.P2PStream<dynamic>>[]),
      ) as _i10.Future<List<_i7.P2PStream<dynamic>>>);

  @override
  _i6.Socket get socket => (super.noSuchMethod(
        Invocation.getter(#socket),
        returnValue: _FakeSocket_5(
          this,
          Invocation.getter(#socket),
        ),
      ) as _i6.Socket);

  @override
  _i10.Future<_i7.P2PStream<dynamic>> newStream(_i12.Context? context) =>
      (super.noSuchMethod(
        Invocation.method(
          #newStream,
          [context],
        ),
        returnValue:
            _i10.Future<_i7.P2PStream<dynamic>>.value(_FakeP2PStream_6<dynamic>(
          this,
          Invocation.method(
            #newStream,
            [context],
          ),
        )),
      ) as _i10.Future<_i7.P2PStream<dynamic>>);

  @override
  _i10.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i13.Uint8List> read([int? length]) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [length],
        ),
        returnValue: _i10.Future<_i13.Uint8List>.value(_i13.Uint8List(0)),
      ) as _i10.Future<_i13.Uint8List>);

  @override
  _i10.Future<void> write(_i13.Uint8List? data) => (super.noSuchMethod(
        Invocation.method(
          #write,
          [data],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void setReadTimeout(Duration? timeout) => super.noSuchMethod(
        Invocation.method(
          #setReadTimeout,
          [timeout],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWriteTimeout(Duration? timeout) => super.noSuchMethod(
        Invocation.method(
          #setWriteTimeout,
          [timeout],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyActivity() => super.noSuchMethod(
        Invocation.method(
          #notifyActivity,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [StreamManagementScope].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamManagementScope extends _i1.Mock
    implements _i5.StreamManagementScope {
  MockStreamManagementScope() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.PeerScope get peerScope => (super.noSuchMethod(
        Invocation.getter(#peerScope),
        returnValue: _FakePeerScope_7(
          this,
          Invocation.getter(#peerScope),
        ),
      ) as _i5.PeerScope);

  @override
  _i5.ScopeStat get stat => (super.noSuchMethod(
        Invocation.getter(#stat),
        returnValue: _FakeScopeStat_8(
          this,
          Invocation.getter(#stat),
        ),
      ) as _i5.ScopeStat);

  @override
  _i10.Future<void> setProtocol(String? protocol) => (super.noSuchMethod(
        Invocation.method(
          #setProtocol,
          [protocol],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void done() => super.noSuchMethod(
        Invocation.method(
          #done,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> reserveMemory(
    int? size,
    int? priority,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reserveMemory,
          [
            size,
            priority,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void releaseMemory(int? size) => super.noSuchMethod(
        Invocation.method(
          #releaseMemory,
          [size],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<_i5.ResourceScopeSpan> beginSpan() => (super.noSuchMethod(
        Invocation.method(
          #beginSpan,
          [],
        ),
        returnValue:
            _i10.Future<_i5.ResourceScopeSpan>.value(_FakeResourceScopeSpan_9(
          this,
          Invocation.method(
            #beginSpan,
            [],
          ),
        )),
      ) as _i10.Future<_i5.ResourceScopeSpan>);

  @override
  _i10.Future<void> setService(String? service) => (super.noSuchMethod(
        Invocation.method(
          #setService,
          [service],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [MuxedStream].
///
/// See the documentation for Mockito's code generation for more information.
class MockMuxedStream extends _i1.Mock implements _i14.MuxedStream {
  MockMuxedStream() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<int>> read(int? length) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [length],
        ),
        returnValue: _i10.Future<List<int>>.value(<int>[]),
      ) as _i10.Future<List<int>>);

  @override
  _i10.Future<void> write(List<int>? data) => (super.noSuchMethod(
        Invocation.method(
          #write,
          [data],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> closeWrite() => (super.noSuchMethod(
        Invocation.method(
          #closeWrite,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> closeRead() => (super.noSuchMethod(
        Invocation.method(
          #closeRead,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  void setDeadline(DateTime? time) => super.noSuchMethod(
        Invocation.method(
          #setDeadline,
          [time],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setReadDeadline(DateTime? time) => super.noSuchMethod(
        Invocation.method(
          #setReadDeadline,
          [time],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWriteDeadline(DateTime? time) => super.noSuchMethod(
        Invocation.method(
          #setWriteDeadline,
          [time],
        ),
        returnValueForMissingStub: null,
      );
}
